### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by devRokas**

### CODE REVIEW

**Review by Citrina2020 — APPROVED** [review]

**Review by lukosiene — APPROVED** [review]

**Review by AleksasKazan — APPROVED** [review]

**Review by Naguali1 — COMMENTED** [review]
good

**Comment by Uranas82** [comment]
Aleksai ar patikrinai?

**Review by Citrina2020 — APPROVED** [review]
looks good

**Review by AleksasKazan — APPROVED** [review]

**Review by lukosiene — APPROVED** [review]
ok

**Review by AleksasKazan — APPROVED** [review]
ok

**Pull request merged**
